"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import SuperAdminDashboard from "./SuperAdminDashboard";
import HyperAdminDashboard from "./HyperAdminDashboard";
import TipDashboard from "./TipDashboard";
import "./attendance-editor.css";
import "./login-password.css";
import "./attendance-pairs.css";
import "./planned-start.css";
import { downloadDailyHoursPdf } from "./dailyHoursPdf";
import { apiUrl } from "./apiUrl";
import { downloadDailyDetailsPdf, type DailyDetail, type DailyEntry } from "./dailyDetailsPdf";

type Person={first:string;last:string;role:string;color:string};
type AttendanceRecord={id:number;name:string;type:"Arrivée"|"Départ";timestamp:string;workDate:string;service?:"matin"|"soir";scheduledStartMinutes:number|null;scheduledMorningStartMinutes?:number|null;scheduledEveningStartMinutes?:number|null};
type AttendancePair={name:string;index:number;arrival?:AttendanceRecord;departure?:AttendanceRecord};
const defaultPeople:Person[]=[
 {first:"Amélie",last:"Martin",role:"Accueil",color:"coral"},{first:"Amine",last:"Bensaïd",role:"Caisse",color:"purple"},{first:"Ambre",last:"Dupont",role:"Service",color:"blue"},{first:"Camille",last:"Robert",role:"Caisse",color:"green"},{first:"Lucas",last:"Bernard",role:"Service",color:"amber"},{first:"Sarah",last:"Petit",role:"Accueil",color:"pink"},{first:"Aniss",last:"Belhaq",role:"Salle",color:"blue"}
];
const api=async(data:object)=>{const token=sessionStorage.getItem("presence-token");const response=await fetch(apiUrl(),{method:"POST",headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify(data)}),raw=await response.text();let result:any;try{result=JSON.parse(raw)}catch{throw new Error(`Réponse invalide du serveur (${response.status}). Vérifiez VITE_API_URL.`)}if(!response.ok||result?.success===false)throw new Error(result.message||"Erreur du serveur");return result;};
const tabForRole=(role:string):"pointage"|"superadmin"|"hyperadmin"=>role==="hyperadmin"?"hyperadmin":role==="superadmin"?"superadmin":"pointage";

function Signature({setValue}:{setValue:(s:string)=>void}){
 const ref=useRef<HTMLCanvasElement>(null),down=useRef(false);
 const pos=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};
 const start=(e:React.PointerEvent<HTMLCanvasElement>)=>{down.current=true;e.currentTarget.setPointerCapture(e.pointerId);const c=e.currentTarget.getContext("2d"),p=pos(e);if(c){c.beginPath();c.moveTo(p.x,p.y);c.strokeStyle="#172139";c.lineWidth=2.5;c.lineCap="round"}};
 const move=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!down.current)return;const c=e.currentTarget.getContext("2d"),p=pos(e);if(c){c.lineTo(p.x,p.y);c.stroke()}};
 const end=()=>{down.current=false;if(ref.current)setValue(ref.current.toDataURL())};
 const clear=()=>{const c=ref.current;if(c){c.getContext("2d")?.clearRect(0,0,c.width,c.height);setValue("")}};
 return <div className="signature"><canvas ref={ref} width="430" height="135" onPointerDown={start} onPointerMove={move} onPointerUp={end}/><em>Signez avec votre doigt ou votre souris</em><button onClick={clear}>Effacer</button></div>
}

export default function AttendanceApp(){
 const[loggedIn,setLoggedIn]=useState(false),[login,setLogin]=useState({username:"",password:""}),[loginError,setLoginError]=useState(""),[showPassword,setShowPassword]=useState(false);
 const[tab,setTab]=useState<"pointage"|"details"|"hours"|"pourboire"|"superadmin"|"hyperadmin">("pointage"),[search,setSearch]=useState(""),[person,setPerson]=useState<Person|null>(null),[sign,setSign]=useState(""),[mode,setMode]=useState("Arrivée"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[adminRole,setAdminRole]=useState(sessionStorage.getItem("presence-role")||"admin");
 const[form,setForm]=useState({cashierMorning:"",cashierEvening:"",fdcMorning:"",fdcEvening:"",fdcFinal:"",cbAmount:"",cashAmount:"",totalAmount:""});
 const[detailEntries,setDetailEntries]=useState<DailyEntry[]>([]),[entryForm,setEntryForm]=useState<DailyEntry>({kind:"depense",label:"",amount:0,note:""});
 const today=()=>new Date().toLocaleDateString("en-CA");
 const[records,setRecords]=useState<AttendanceRecord[]>([]),[reportDate,setReportDate]=useState(today()),[editingTime,setEditingTime]=useState<Record<number,string>>({});
 const[team,setTeam]=useState<Person[]>(defaultPeople),[managing,setManaging]=useState(false),[newPerson,setNewPerson]=useState({first:"",last:"",role:""});
 const[now,setNow]=useState(()=>new Date());
 const[selectedHasOpenArrival,setSelectedHasOpenArrival]=useState(false),[selectedShift,setSelectedShift]=useState<"matin"|"soir">("matin"),[plannedStart,setPlannedStart]=useState<number|null>(null),[statusLoading,setStatusLoading]=useState(false);
 const filtered=useMemo(()=>team.filter(p=>`${p.first} ${p.last}`.toLowerCase().startsWith(search.trim().toLowerCase())),[search,team]);
 useEffect(()=>{const timer=window.setInterval(()=>setNow(new Date()),1000);return()=>window.clearInterval(timer)},[]);
 useEffect(()=>{if(!person){setSelectedHasOpenArrival(false);setSelectedShift("matin");setPlannedStart(null);return}let cancelled=false;const loadStatus=async()=>{setStatusLoading(true);try{const result=await api({action:"attendanceStatus",name:`${person.first} ${person.last}`,workDate:today()});if(!cancelled){const open=Boolean(result.hasOpenArrival);setSelectedHasOpenArrival(open);setSelectedShift(result.nextShift==="soir"?"soir":"matin");setPlannedStart(result.scheduledStartMinutes??null);setMode(open?"Départ":"Arrivée")}}catch(error){if(!cancelled)setMessage(error instanceof Error?error.message:"Statut du pointage inaccessible")}finally{if(!cancelled)setStatusLoading(false)}};void loadStatus();return()=>{cancelled=true}},[person]);
 useEffect(()=>{const role=sessionStorage.getItem("presence-role")||"admin";setLoggedIn(Boolean(sessionStorage.getItem("presence-token")));setAdminRole(role);setTab(tabForRole(role));const loadEmployees=async()=>{try{const response=await fetch(apiUrl(`?action=employees&t=${Date.now()}`),{cache:"no-store"});if(!response.ok)throw new Error();const employees:Person[]=await response.json();if(!Array.isArray(employees))throw new Error();setTeam(employees)}catch{setMessage("Le backend SQLite est inaccessible.")}};void loadEmployees()},[]);
 useEffect(()=>{if(!loggedIn||adminRole!=="admin")return;let cancelled=false;setRecords([]);const loadReport=async()=>{try{const result=await api({action:"report",workDate:reportDate});if(!cancelled)setRecords(result.records||[])}catch{/* la session sera vérifiée à la prochaine action */}};void loadReport();return()=>{cancelled=true}},[loggedIn,adminRole,reportDate]);
 useEffect(()=>{if(!loggedIn||adminRole!=="admin"||tab!=="details")return;const loadDetails=async()=>{try{const result=await api({action:"dailyDetails",workDate:reportDate});if(result.detail)setForm({cashierMorning:result.detail.cashierMorning||"",cashierEvening:result.detail.cashierEvening||"",fdcMorning:result.detail.fdcMorning||"",fdcEvening:result.detail.fdcEvening||"",fdcFinal:result.detail.fdcFinal||"",cbAmount:result.detail.cbAmount||"",cashAmount:result.detail.cashAmount||"",totalAmount:result.detail.totalAmount||""});else setForm({cashierMorning:"",cashierEvening:"",fdcMorning:"",fdcEvening:"",fdcFinal:"",cbAmount:"",cashAmount:"",totalAmount:""});setDetailEntries(result.entries||[])}catch(error){setMessage(error instanceof Error?error.message:"Chargement des détails impossible")}};void loadDetails()},[loggedIn,adminRole,tab,reportDate]);
 const saveTeam=(next:Person[])=>{setTeam(next);localStorage.setItem("presence-team",JSON.stringify(next))};
 const addPerson=async(e:React.FormEvent)=>{e.preventDefault();const first=newPerson.first.trim(),last=newPerson.last.trim(),role=newPerson.role.trim();if(!first||!last||!role)return;const colors=["coral","purple","blue","green","amber","pink"],color=colors[team.length%colors.length];setBusy(true);try{await api({action:"addEmployee",first,last,role,color});saveTeam([...team,{first,last,role,color}]);setNewPerson({first:"",last:"",role:""});setMessage(`${first} ${last} a été ajouté dans Google Sheets.`)}catch(error){setMessage(error instanceof Error?error.message:"Ajout impossible")}finally{setBusy(false)}};
 const removePerson=async(target:Person)=>{setBusy(true);try{await api({action:"deleteEmployee",first:target.first,last:target.last});saveTeam(team.filter(p=>!(p.first===target.first&&p.last===target.last)));if(person?.first===target.first&&person?.last===target.last)setPerson(null);setMessage(`${target.first} ${target.last} a été supprimé de Google Sheets.`)}catch(error){setMessage(error instanceof Error?error.message:"Suppression impossible")}finally{setBusy(false)}};
 const authenticate=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{const result=await api({action:"login",username:login.username,password:login.password}),role=String(result.role||"admin");sessionStorage.setItem("presence-token",result.token);sessionStorage.setItem("presence-role",role);setAdminRole(role);setTab(tabForRole(role));setLoggedIn(true);setLoginError("")}catch(error){setLoginError(error instanceof Error?error.message:"Connexion impossible")}finally{setBusy(false)}};
 const logout=async()=>{try{await api({action:"logout"})}catch{/* fermeture locale même si le serveur est indisponible */}sessionStorage.removeItem("presence-token");sessionStorage.removeItem("presence-role");setAdminRole("admin");setLoggedIn(false);setTab("pointage");setLogin({username:"",password:""})};
 const submit=async()=>{if(!person||!sign)return;setBusy(true);try{const now=new Date(),name=`${person.first} ${person.last}`;let workDate=today();if(mode==="Départ"){const own=records.filter(r=>r.name===name).sort((a,b)=>a.timestamp.localeCompare(b.timestamp));const lastIn=[...own].reverse().find(r=>r.type==="Arrivée"),lastOut=[...own].reverse().find(r=>r.type==="Départ");if(lastIn&&(!lastOut||lastIn.timestamp>lastOut.timestamp))workDate=lastIn.workDate}const saved=await api({action:"pointage",mode,name,signature:sign,date:now.toISOString(),workDate});const result=await api({action:"report",workDate});setRecords(result.records||[]);setReportDate(workDate);const service=mode==="Arrivée"?` (${saved.shift==="soir"?"service du soir":"service du matin"})`:"";setMessage(`${mode} enregistrée${service} pour ${person.first}.`);setPerson(null);setSign("");setSearch("")}catch(error){setMessage(error instanceof Error?error.message:"L’enregistrement a échoué. Réessayez.")}finally{setBusy(false)}};
 const attendancePairs=useMemo(()=>{const pairs:AttendancePair[]=[];for(const record of [...records].sort((a,b)=>a.name.localeCompare(b.name)||a.timestamp.localeCompare(b.timestamp))){if(record.type==="Arrivée")pairs.push({name:record.name,index:pairs.filter(pair=>pair.name===record.name).length+1,arrival:record});else{const open=[...pairs].reverse().find(pair=>pair.name===record.name&&pair.arrival&&!pair.departure);if(open)open.departure=record;else pairs.push({name:record.name,index:pairs.filter(pair=>pair.name===record.name).length+1,departure:record})}}return pairs},[records]);
 const updateAttendancePair=async(pair:AttendancePair)=>{const entries=[pair.arrival,pair.departure].filter((record):record is AttendanceRecord=>Boolean(record));setBusy(true);try{for(const record of entries){const value=editingTime[record.id]??new Date(record.timestamp).toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"});if(!/^\d{2}:\d{2}$/.test(value))continue;const changed=new Date(record.timestamp),[hours,minutes]=value.split(":").map(Number);changed.setHours(hours,minutes,0,0);await api({action:"updateAttendance",id:record.id,timestamp:changed.toISOString()})}const result=await api({action:"report",workDate:reportDate});setRecords(result.records||[]);setEditingTime(current=>{const next={...current};entries.forEach(record=>delete next[record.id]);return next});setMessage(`Horaires de ${pair.name} modifiés.`)}catch(error){setMessage(error instanceof Error?error.message:"Modification impossible")}finally{setBusy(false)}};
 const deleteAttendancePair=async(pair:AttendancePair)=>{if(!confirm(`Supprimer le service ${pair.index} de ${pair.name} ?`))return;const ids=[pair.arrival?.id,pair.departure?.id].filter((id):id is number=>typeof id==="number");setBusy(true);try{await api({action:"deleteAttendancePair",ids});const result=await api({action:"report",workDate:reportDate});setRecords(result.records||[]);setMessage(`Service ${pair.index} de ${pair.name} supprimé.`)}catch(error){setMessage(error instanceof Error?error.message:"Suppression impossible")}finally{setBusy(false)}};
 const summary=(p:Person)=>{const events=records.filter(r=>r.name===`${p.first} ${p.last}`&&r.workDate===reportDate).sort((a,b)=>a.timestamp.localeCompare(b.timestamp));const parisTime=(date:Date)=>{const parts=new Intl.DateTimeFormat("fr-FR",{timeZone:"Europe/Paris",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(date),part=(type:string)=>Number(parts.find(item=>item.type===type)?.value||0);return{hour:part("hour"),minutes:part("hour")*60+part("minute")}},shifts:{start?:Date;end?:Date;period:"matin"|"soir"}[]=[];for(const event of events){if(event.type==="Arrivée"){const arrival=new Date(event.timestamp),arrivalTime=parisTime(arrival),period=arrivalTime.hour>=15?"soir":"matin",scheduled=period==="soir"?event.scheduledEveningStartMinutes:event.scheduledMorningStartMinutes;let start=arrival;if(scheduled!=null&&arrivalTime.minutes<scheduled)start=new Date(arrival.getTime()+(scheduled-arrivalTime.minutes)*60000);shifts.push({start,period})}else{const open=[...shifts].reverse().find(s=>s.start&&!s.end);if(open)open.end=new Date(event.timestamp)}}const ordered=[shifts.find(shift=>shift.period==="matin"),shifts.find(shift=>shift.period==="soir")],duration=(s?:{start?:Date;end?:Date})=>{if(!s?.start||!s.end)return 0;const day=24*60*60*1000,difference=s.end.getTime()-s.start.getTime();return ((difference%day)+day)%day/3600000};const time=(d?:Date)=>d?d.toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"}):"00:00";return{name:`${p.first} ${p.last}`,start1:time(ordered[0]?.start),end1:time(ordered[0]?.end),hours1:duration(ordered[0]),start2:time(ordered[1]?.start),end2:time(ordered[1]?.end),hours2:duration(ordered[1])}};
 const downloadReport=async()=>{setBusy(true);try{const result=await api({action:"report",workDate:reportDate}),freshRecords=result.records||[];setRecords(freshRecords);downloadDailyHoursPdf(reportDate,team,freshRecords)}catch(error){setMessage(error instanceof Error?error.message:"Téléchargement impossible")}finally{setBusy(false)}};
 const addDetailEntry=()=>{const label=entryForm.label.trim(),amount=Number(entryForm.amount);if(!label||!Number.isFinite(amount)||amount<0)return;setDetailEntries(entries=>[...entries,{...entryForm,label,amount}]);setEntryForm({kind:"depense",label:"",amount:0,note:""})};
 const add=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await api({action:"details",...form,entries:detailEntries,workDate:reportDate,date:new Date().toISOString()});setMessage("Les détails, dépenses et offerts ont été enregistrés.")}catch(error){setMessage(error instanceof Error?error.message:"L’ajout a échoué. Réessayez.")}finally{setBusy(false)}};
 const downloadDetails=async()=>{try{const result=await api({action:"dailyDetails",workDate:reportDate});if(!result.detail)throw new Error("Enregistrez d’abord les détails de cette journée");downloadDailyDetailsPdf(result.detail as DailyDetail,result.entries||[])}catch(error){setMessage(error instanceof Error?error.message:"Téléchargement impossible")}};
 if(!loggedIn)return <main className="login-page"><section className="login-card"><div className="login-logo">P</div><div className="login-title"><small>ESPACE SÉCURISÉ</small><h1>Bienvenue</h1><p>Connectez-vous pour accéder au registre d’équipe.</p></div><form onSubmit={authenticate}><label>Identifiant<input autoFocus required value={login.username} onChange={e=>setLogin({...login,username:e.target.value})} placeholder="Votre identifiant" autoComplete="username"/></label><label className="password-field">Mot de passe<input required type={showPassword?"text":"password"} value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} placeholder="Votre mot de passe" autoComplete="current-password"/><button className="password-eye" type="button" onClick={()=>setShowPassword(value=>!value)} aria-label={showPassword?"Masquer le mot de passe":"Afficher le mot de passe"}>{showPassword?"◉":"◌"}</button></label>{loginError&&<p className="login-error">{loginError}</p>}<button className="login-submit">Se connecter <span>→</span></button></form><p className="login-help">Accès administrateur · Registre Présence</p></section></main>;
 return <main>
  <header><div className="brand"><b>P</b></div><div className="header-actions"><div className="date"><i/>{new Intl.DateTimeFormat("fr-FR",{weekday:"long",day:"numeric",month:"long"}).format(now)}</div><button className="logout" onClick={logout}>Déconnexion</button></div></header>
  <section className="shell">
   <div className="hero"><label>{tab==="superadmin"?"SUPER ADMINISTRATION":"ESPACE ÉQUIPE"}</label><h1>{tab==="pointage"?"Bonjour, prêt à pointer ?":tab==="details"?"Détail journalier":tab==="hours"?"Heures des employés":tab==="pourboire"?"Pourboires de l’équipe":"Pilotez votre établissement"}</h1><p>{tab==="pointage"?"Recherchez votre nom, signez, puis validez votre passage.":tab==="details"?"Renseignez les caisses, dépenses et offerts de la journée.":tab==="hours"?"Consultez, corrigez et exportez les horaires des employés.":tab==="pourboire"?"Répartissez les pourboires et suivez les parts non récupérées.":"Une vue claire sur l’équipe, les accès et l’activité BEEF HOUSE."}</p></div>
   <nav className={adminRole==="superadmin"?"super-only-nav":adminRole==="admin"?"admin-nav":""}>{adminRole==="admin"&&<><button className={tab==="pointage"?"active":""} onClick={()=>{setTab("pointage");setMessage("")}}>✓ &nbsp; Pointage</button><button className={tab==="details"?"active":""} onClick={()=>{setTab("details");setMessage("")}}>≡ &nbsp; Détail journalier</button><button className={tab==="hours"?"active":""} onClick={()=>{setTab("hours");setMessage("")}}>◷ &nbsp; Heures employés</button><button className={tab==="pourboire"?"active":""} onClick={()=>{setTab("pourboire");setMessage("")}}>€ &nbsp; Pourboire</button></>}{adminRole==="superadmin"&&<button className="active">◆ &nbsp; Super Admin</button>}</nav>
   {message&&<div className="message">✓ &nbsp; {message}<button onClick={()=>setMessage("")}>×</button></div>}
   {tab==="pointage"?<div className="grid">
    <section className="card"><div className="cardhead"><span>1</span><div><h2>Trouvez votre nom</h2><p>Tapez les premières lettres de votre prénom.</p></div><div className="team-actions"><small>{team.length} personnes</small><button onClick={()=>setManaging(!managing)}>{managing?"Fermer":"＋ Gérer"}</button></div></div>
     {managing&&<div className="team-manager"><form onSubmit={addPerson}><input required value={newPerson.first} onChange={e=>setNewPerson({...newPerson,first:e.target.value})} placeholder="Prénom"/><input required value={newPerson.last} onChange={e=>setNewPerson({...newPerson,last:e.target.value})} placeholder="Nom"/><input required value={newPerson.role} onChange={e=>setNewPerson({...newPerson,role:e.target.value})} placeholder="Poste"/><button>Ajouter</button></form><div className="manage-list">{team.map(p=><div key={`${p.first}-${p.last}`}><span><b>{p.first} {p.last}</b><small>{p.role}</small></span><button onClick={()=>removePerson(p)} aria-label={`Supprimer ${p.first} ${p.last}`}>Supprimer</button></div>)}</div></div>}
     <label className="search">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ex. AM pour Amélie, Amine..."/><kbd>A—Z</kbd></label>
     <div className="list">{filtered.map(p=><button key={`${p.first}-${p.last}`} className={`person ${person?.first===p.first&&person?.last===p.last?"selected":""}`} onClick={()=>{setPerson(p);setSign("")}}><b className={p.color}>{p.first[0]}{p.last[0]}</b><span><strong>{p.first} {p.last}</strong><small>{p.role}</small></span><i>{person?.first===p.first&&person?.last===p.last?"✓":""}</i></button>)}{!filtered.length&&<p className="empty">Aucun nom trouvé.</p>}</div>
    </section>
    <section className={`card signcard ${!person?"disabled":""}`}><div className="cardhead"><span>2</span><div><h2>Signez et validez</h2><p>{person?`Pointage de ${person.first} ${person.last}`:"Sélectionnez d’abord votre nom."}</p></div></div>
     <div className="switch"><button disabled={selectedHasOpenArrival} className={mode==="Arrivée"?"active":""} onClick={()=>setMode("Arrivée")}>↘ {selectedHasOpenArrival?"Arrivée déjà pointée":selectedShift==="soir"?"Arrivée soir":"Arrivée matin"}</button><button disabled={!selectedHasOpenArrival} className={mode==="Départ"?"active":""} onClick={()=>setMode("Départ")}>↗ Départ {selectedShift==="soir"?"soir":"matin"}</button></div>
     {person&&<p className="planned-start">Planning vérifié · Service {selectedShift} {plannedStart!==null?`prévu à ${String(Math.floor(plannedStart/60)%24).padStart(2,"0")}:${String(plannedStart%60).padStart(2,"0")}`:"sans horaire programmé"}</p>}
     <div className="time"><small>HEURE ACTUELLE</small><strong>{new Intl.DateTimeFormat("fr-FR",{hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(now)}</strong></div><label className="caption">VOTRE SIGNATURE</label>
     <Signature key={person?.first||"none"} setValue={setSign}/><button className="primary" disabled={!person||!sign||busy||statusLoading||(mode==="Arrivée"&&selectedHasOpenArrival)||(mode==="Départ"&&!selectedHasOpenArrival)} onClick={submit}>{statusLoading?"Vérification...":busy?"Enregistrement...":`Valider mon ${mode.toLowerCase()}`} →</button><p className="privacy">🔒 Votre signature sert uniquement à confirmer ce pointage.</p>
    </section>
   </div>:tab==="details"?<div className="grid details admin-single-panel">
    <section className="card daily-detail-card"><div className="cardhead"><span>1</span><div><h2>Détail journalier</h2><p>Caisses, dépenses et offerts de la journée.</p></div></div><form onSubmit={add}>
     <div className="detail-toolbar"><label>Date<input type="date" value={reportDate} onChange={e=>setReportDate(e.target.value)}/></label><button type="button" onClick={downloadDetails}>↓ Télécharger le document</button></div>
     <h3>MATIN</h3><div className="fields"><label>Caissier du matin<input required value={form.cashierMorning} onChange={e=>setForm({...form,cashierMorning:e.target.value})} placeholder="Nom et prénom"/></label><label>FDC initial / matin<input required value={form.fdcMorning} onChange={e=>setForm({...form,fdcMorning:e.target.value})} placeholder="Ex. 250,00 €"/></label></div>
     <h3 className="night">SOIR</h3><div className="fields"><label>Caissier du soir<input required value={form.cashierEvening} onChange={e=>setForm({...form,cashierEvening:e.target.value})} placeholder="Nom et prénom"/></label><label>FDC du soir<input required value={form.fdcEvening} onChange={e=>setForm({...form,fdcEvening:e.target.value})} placeholder="Ex. 248,50 €"/></label></div>
     <h3 className="finance-title">DÉPENSES &amp; OFFERTS</h3><div className="entry-builder"><select value={entryForm.kind} onChange={e=>setEntryForm({...entryForm,kind:e.target.value as DailyEntry["kind"]})}><option value="depense">Dépense</option><option value="offert">Offert</option></select><input value={entryForm.label} onChange={e=>setEntryForm({...entryForm,label:e.target.value})} placeholder="Libellé"/><input type="number" min="0" step="0.01" value={entryForm.amount||""} onChange={e=>setEntryForm({...entryForm,amount:Number(e.target.value)})} placeholder="Montant €"/><button type="button" onClick={addDetailEntry}>＋</button></div>
     <div className="daily-entry-list">{detailEntries.map((entry,index)=><div key={`${entry.kind}-${entry.label}-${index}`}><span className={entry.kind}>{entry.kind==="depense"?"Dépense":"Offert"}</span><b>{entry.label}</b><strong>{entry.amount.toFixed(2)} €</strong><button type="button" onClick={()=>setDetailEntries(entries=>entries.filter((_,entryIndex)=>entryIndex!==index))}>×</button></div>)}{!detailEntries.length&&<small>Aucune dépense ni offert ajouté.</small>}</div>
     <h3 className="night">CLÔTURE</h3><div className="fields"><label>FDC final<input value={form.fdcFinal} onChange={e=>setForm({...form,fdcFinal:e.target.value})} placeholder="Ex. 151,80 €"/></label><label>CB<input value={form.cbAmount} onChange={e=>setForm({...form,cbAmount:e.target.value})} placeholder="Montant carte"/></label><label>ESP<input value={form.cashAmount} onChange={e=>setForm({...form,cashAmount:e.target.value})} placeholder="Montant espèces"/></label><label>Total<input value={form.totalAmount} onChange={e=>setForm({...form,totalAmount:e.target.value})} placeholder="Total journée"/></label></div>
     <button className="primary full" disabled={busy}>{busy?"Enregistrement...":"Enregistrer le détail journalier ＋"}</button>
    </form></section>
   </div>:tab==="hours"?<div className="grid details admin-single-panel">
    <section className="card report-card"><div className="cardhead"><span>1</span><div><h2>Heures des employés</h2><p>Calcul automatique et correction des pointages.</p></div></div><div className="report-tools"><label>Date<input type="date" value={reportDate} onChange={e=>setReportDate(e.target.value)}/></label><button disabled={busy} onClick={downloadReport}>{busy?"Chargement…":"↓ Télécharger le PDF"}</button></div><div className="report-table"><table><thead><tr><th>Employé</th><th>Début 1</th><th>Fin 1</th><th>MIDI</th><th>Début 2</th><th>Fin 2</th><th>SOIR</th><th>Total</th></tr></thead><tbody>{team.map(p=>{const s=summary(p);return <tr key={`${p.first}-${p.last}`}><td>{s.name}</td><td>{s.start1}</td><td>{s.end1}</td><td>{s.hours1.toFixed(2)}</td><td>{s.start2}</td><td>{s.end2}</td><td>{s.hours2.toFixed(2)}</td><td><b>{(s.hours1+s.hours2).toFixed(2)}</b></td></tr>})}</tbody></table></div><div className="attendance-editor"><h3>CORRIGER UN HORAIRE</h3>{attendancePairs.length?attendancePairs.map(pair=><div className="attendance-edit-row attendance-pair-row" key={`${pair.name}-${pair.index}`}><span><b>{pair.name}</b><small>Service {pair.index}</small></span><label>Arrivée<input disabled={!pair.arrival} type="time" value={pair.arrival?(editingTime[pair.arrival.id]??new Date(pair.arrival.timestamp).toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"})):""} onChange={e=>pair.arrival&&setEditingTime({...editingTime,[pair.arrival.id]:e.target.value})}/></label><label>Départ<input disabled={!pair.departure} type="time" value={pair.departure?(editingTime[pair.departure.id]??new Date(pair.departure.timestamp).toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"})):""} onChange={e=>pair.departure&&setEditingTime({...editingTime,[pair.departure.id]:e.target.value})}/></label><button disabled={busy} onClick={()=>updateAttendancePair(pair)}>Modifier</button><button className="delete-attendance" disabled={busy} onClick={()=>deleteAttendancePair(pair)} title="Supprimer cet horaire" aria-label={`Supprimer le service ${pair.index} de ${pair.name}`}>×</button></div>):<p>Aucun pointage pour cette date.</p>}</div></section>
   </div>:tab==="pourboire"?<TipDashboard/>:tab==="hyperadmin"?<HyperAdminDashboard/>:<SuperAdminDashboard/>}
  </section><footer><b>Présence</b><span>Pointage simple, équipe sereine.</span><small><i/> Synchronisation Google prête</small></footer>
 </main>
}
