"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import SuperAdminDashboard from "./SuperAdminDashboard";
import "./attendance-editor.css";
import "./login-password.css";
import "./attendance-pairs.css";
import { downloadDailyExcel } from "./dailyExcel";
import { apiUrl } from "./apiUrl";

type Person={first:string;last:string;role:string;color:string};
type AttendanceRecord={id:number;name:string;type:"Arrivée"|"Départ";timestamp:string;workDate:string;scheduledStartMinutes:number|null};
type AttendancePair={name:string;index:number;arrival?:AttendanceRecord;departure?:AttendanceRecord};
const defaultPeople:Person[]=[
 {first:"Amélie",last:"Martin",role:"Accueil",color:"coral"},{first:"Amine",last:"Bensaïd",role:"Caisse",color:"purple"},{first:"Ambre",last:"Dupont",role:"Service",color:"blue"},{first:"Camille",last:"Robert",role:"Caisse",color:"green"},{first:"Lucas",last:"Bernard",role:"Service",color:"amber"},{first:"Sarah",last:"Petit",role:"Accueil",color:"pink"},{first:"Aniss",last:"Belhaq",role:"Salle",color:"blue"}
];
const api=async(data:object)=>{const token=sessionStorage.getItem("presence-token");const response=await fetch(apiUrl(),{method:"POST",headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify(data)});const result=await response.json();if(!response.ok||result?.success===false)throw new Error(result.message||"Erreur du serveur");return result;};

function Signature({setValue}:{setValue:(s:string)=>void}){
 const ref=useRef<HTMLCanvasElement>(null),down=useRef(false);
 const pos=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};
 const start=(e:React.PointerEvent<HTMLCanvasElement>)=>{down.current=true;e.currentTarget.setPointerCapture(e.pointerId);const c=e.currentTarget.getContext("2d"),p=pos(e);if(c){c.beginPath();c.moveTo(p.x,p.y);c.strokeStyle="#172139";c.lineWidth=2.5;c.lineCap="round"}};
 const move=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!down.current)return;const c=e.currentTarget.getContext("2d"),p=pos(e);if(c){c.lineTo(p.x,p.y);c.stroke()}};
 const end=()=>{down.current=false;if(ref.current)setValue(ref.current.toDataURL())};
 const clear=()=>{const c=ref.current;if(c){c.getContext("2d")?.clearRect(0,0,c.width,c.height);setValue("")}};
 return <div className="signature"><canvas ref={ref} width="430" height="135" onPointerDown={start} onPointerMove={move} onPointerUp={end}/><em>Signez avec votre doigt ou votre souris</em><button onClick={clear}>Effacer</button></div>
}

export default function AttendanceApp(){
 const[loggedIn,setLoggedIn]=useState(false),[login,setLogin]=useState({username:"",password:""}),[loginError,setLoginError]=useState(""),[showPassword,setShowPassword]=useState(false);
 const[tab,setTab]=useState<"pointage"|"details"|"superadmin">("pointage"),[search,setSearch]=useState(""),[person,setPerson]=useState<Person|null>(null),[sign,setSign]=useState(""),[mode,setMode]=useState("Arrivée"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[adminRole,setAdminRole]=useState(sessionStorage.getItem("presence-role")||"admin");
 const[form,setForm]=useState({cashierMorning:"",cashierEvening:"",fdcMorning:"",fdcEvening:""});
 const[rows,setRows]=useState<typeof form[]>([]);
 const today=()=>new Date().toLocaleDateString("en-CA");
 const[records,setRecords]=useState<AttendanceRecord[]>([]),[reportDate,setReportDate]=useState(today()),[editingTime,setEditingTime]=useState<Record<number,string>>({});
 const[team,setTeam]=useState<Person[]>(defaultPeople),[managing,setManaging]=useState(false),[newPerson,setNewPerson]=useState({first:"",last:"",role:""});
 const filtered=useMemo(()=>team.filter(p=>`${p.first} ${p.last}`.toLowerCase().startsWith(search.trim().toLowerCase())),[search,team]);
 useEffect(()=>{const role=sessionStorage.getItem("presence-role")||"admin";setLoggedIn(Boolean(sessionStorage.getItem("presence-token")));setAdminRole(role);setTab(role==="superadmin"?"superadmin":"pointage");const loadEmployees=async()=>{try{const response=await fetch(apiUrl(`?action=employees&t=${Date.now()}`),{cache:"no-store"});if(!response.ok)throw new Error();const employees:Person[]=await response.json();if(!Array.isArray(employees))throw new Error();setTeam(employees)}catch{setMessage("Le backend SQLite est inaccessible.")}};void loadEmployees()},[]);
 useEffect(()=>{if(!loggedIn||adminRole!=="admin")return;const loadReport=async()=>{try{const result=await api({action:"report",workDate:reportDate});setRecords(result.records||[])}catch{/* la session sera vérifiée à la prochaine action */}};void loadReport()},[loggedIn,adminRole,reportDate]);
 const saveTeam=(next:Person[])=>{setTeam(next);localStorage.setItem("presence-team",JSON.stringify(next))};
 const addPerson=async(e:React.FormEvent)=>{e.preventDefault();const first=newPerson.first.trim(),last=newPerson.last.trim(),role=newPerson.role.trim();if(!first||!last||!role)return;const colors=["coral","purple","blue","green","amber","pink"],color=colors[team.length%colors.length];setBusy(true);try{await api({action:"addEmployee",first,last,role,color});saveTeam([...team,{first,last,role,color}]);setNewPerson({first:"",last:"",role:""});setMessage(`${first} ${last} a été ajouté dans Google Sheets.`)}catch(error){setMessage(error instanceof Error?error.message:"Ajout impossible")}finally{setBusy(false)}};
 const removePerson=async(target:Person)=>{setBusy(true);try{await api({action:"deleteEmployee",first:target.first,last:target.last});saveTeam(team.filter(p=>!(p.first===target.first&&p.last===target.last)));if(person?.first===target.first&&person?.last===target.last)setPerson(null);setMessage(`${target.first} ${target.last} a été supprimé de Google Sheets.`)}catch(error){setMessage(error instanceof Error?error.message:"Suppression impossible")}finally{setBusy(false)}};
 const authenticate=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{const result=await api({action:"login",username:login.username,password:login.password});sessionStorage.setItem("presence-token",result.token);sessionStorage.setItem("presence-role",result.role||"admin");setAdminRole(result.role||"admin");setLoggedIn(true);setTab(result.role==="superadmin"?"superadmin":"pointage");setLoginError("")}catch(error){setLoginError(error instanceof Error?error.message:"Connexion impossible")}finally{setBusy(false)}};
 const logout=async()=>{try{await api({action:"logout"})}catch{/* fermeture locale même si le serveur est indisponible */}sessionStorage.removeItem("presence-token");sessionStorage.removeItem("presence-role");setAdminRole("admin");setLoggedIn(false);setTab("pointage");setLogin({username:"",password:""})};
 const submit=async()=>{if(!person||!sign)return;setBusy(true);try{const now=new Date(),name=`${person.first} ${person.last}`;let workDate=today();if(mode==="Départ"){const own=records.filter(r=>r.name===name).sort((a,b)=>a.timestamp.localeCompare(b.timestamp));const lastIn=[...own].reverse().find(r=>r.type==="Arrivée"),lastOut=[...own].reverse().find(r=>r.type==="Départ");if(lastIn&&(!lastOut||lastIn.timestamp>lastOut.timestamp))workDate=lastIn.workDate}await api({action:"pointage",mode,name,signature:sign,date:now.toISOString(),workDate});const result=await api({action:"report",workDate});setRecords(result.records||[]);setReportDate(workDate);setMessage(`${mode} enregistrée pour ${person.first}.`);setPerson(null);setSign("");setSearch("")}catch{setMessage("L’enregistrement a échoué. Réessayez.")}finally{setBusy(false)}};
 const attendancePairs=useMemo(()=>{const pairs:AttendancePair[]=[];for(const record of [...records].sort((a,b)=>a.name.localeCompare(b.name)||a.timestamp.localeCompare(b.timestamp))){if(record.type==="Arrivée")pairs.push({name:record.name,index:pairs.filter(pair=>pair.name===record.name).length+1,arrival:record});else{const open=[...pairs].reverse().find(pair=>pair.name===record.name&&pair.arrival&&!pair.departure);if(open)open.departure=record;else pairs.push({name:record.name,index:pairs.filter(pair=>pair.name===record.name).length+1,departure:record})}}return pairs},[records]);
 const updateAttendancePair=async(pair:AttendancePair)=>{const entries=[pair.arrival,pair.departure].filter((record):record is AttendanceRecord=>Boolean(record));setBusy(true);try{for(const record of entries){const value=editingTime[record.id]??new Date(record.timestamp).toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"});if(!/^\d{2}:\d{2}$/.test(value))continue;const changed=new Date(record.timestamp),[hours,minutes]=value.split(":").map(Number);changed.setHours(hours,minutes,0,0);await api({action:"updateAttendance",id:record.id,timestamp:changed.toISOString()})}const result=await api({action:"report",workDate:reportDate});setRecords(result.records||[]);setEditingTime(current=>{const next={...current};entries.forEach(record=>delete next[record.id]);return next});setMessage(`Horaires de ${pair.name} modifiés.`)}catch(error){setMessage(error instanceof Error?error.message:"Modification impossible")}finally{setBusy(false)}};
 const summary=(p:Person)=>{const events=records.filter(r=>r.name===`${p.first} ${p.last}`&&r.workDate===reportDate).sort((a,b)=>a.timestamp.localeCompare(b.timestamp));const shifts:{start?:Date;end?:Date}[]=[];for(const event of events){if(event.type==="Arrivée"){let start=new Date(event.timestamp);if(!shifts.length&&event.scheduledStartMinutes!==null){const planned=new Date(`${event.workDate}T00:00:00`);planned.setMinutes(event.scheduledStartMinutes);if(start<planned)start=planned}shifts.push({start})}else{const open=[...shifts].reverse().find(s=>s.start&&!s.end);if(open)open.end=new Date(event.timestamp)}}const duration=(s?:{start?:Date;end?:Date})=>s?.start&&s.end?Math.max(0,(s.end.getTime()-s.start.getTime())/3600000):0;const time=(d?:Date)=>d?d.toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"}):"00:00";return{name:`${p.first} ${p.last}`,start1:time(shifts[0]?.start),end1:time(shifts[0]?.end),hours1:duration(shifts[0]),start2:time(shifts[1]?.start),end2:time(shifts[1]?.end),hours2:duration(shifts[1])}};
 const downloadReport=()=>downloadDailyExcel(reportDate,team,records);
 const add=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await api({action:"details",...form,date:new Date().toISOString()});setRows(r=>[form,...r]);setForm({cashierMorning:"",cashierEvening:"",fdcMorning:"",fdcEvening:""});setMessage("La ligne a été ajoutée au registre.")}catch{setMessage("L’ajout a échoué. Réessayez.")}finally{setBusy(false)}};
 if(!loggedIn)return <main className="login-page"><section className="login-card"><div className="login-logo">P</div><div className="login-title"><small>ESPACE SÉCURISÉ</small><h1>Bienvenue</h1><p>Connectez-vous pour accéder au registre d’équipe.</p></div><form onSubmit={authenticate}><label>Identifiant<input autoFocus required value={login.username} onChange={e=>setLogin({...login,username:e.target.value})} placeholder="Votre identifiant" autoComplete="username"/></label><label className="password-field">Mot de passe<input required type={showPassword?"text":"password"} value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} placeholder="Votre mot de passe" autoComplete="current-password"/><button className="password-eye" type="button" onClick={()=>setShowPassword(value=>!value)} aria-label={showPassword?"Masquer le mot de passe":"Afficher le mot de passe"}>{showPassword?"◉":"◌"}</button></label>{loginError&&<p className="login-error">{loginError}</p>}<button className="login-submit">Se connecter <span>→</span></button></form><p className="login-help">Accès administrateur · Registre Présence</p></section></main>;
 return <main>
  <header><div className="brand"><b>P</b><span><strong>Présence</strong><small>Registre d’équipe</small></span></div><div className="header-actions"><div className="date"><i/>{new Intl.DateTimeFormat("fr-FR",{weekday:"long",day:"numeric",month:"long"}).format(new Date())}</div><button className="logout" onClick={logout}>Déconnexion</button></div></header>
  <section className="shell">
   <div className="hero"><label>{tab==="superadmin"?"SUPER ADMINISTRATION":"ESPACE ÉQUIPE"}</label><h1>{tab==="pointage"?"Bonjour, prêt à pointer ?":tab==="details"?"Suivi de la journée":"Pilotez votre établissement"}</h1><p>{tab==="pointage"?"Recherchez votre nom, signez, puis validez votre passage.":tab==="details"?"Renseignez les responsables et les fonds de caisse de chaque service.":"Une vue claire sur l’équipe, les accès et l’activité BEEF HOUSE."}</p></div>
   <nav className={adminRole==="superadmin"?"super-only-nav":""}>{adminRole==="admin"&&<><button className={tab==="pointage"?"active":""} onClick={()=>{setTab("pointage");setMessage("")}}>✓ &nbsp; Pointage</button><button className={tab==="details"?"active":""} onClick={()=>{setTab("details");setMessage("")}}>≡ &nbsp; Détails</button></>}{adminRole==="superadmin"&&<button className="active">◆ &nbsp; Super Admin</button>}</nav>
   {message&&<div className="message">✓ &nbsp; {message}<button onClick={()=>setMessage("")}>×</button></div>}
   {tab==="pointage"?<div className="grid">
    <section className="card"><div className="cardhead"><span>1</span><div><h2>Trouvez votre nom</h2><p>Tapez les premières lettres de votre prénom.</p></div><div className="team-actions"><small>{team.length} personnes</small><button onClick={()=>setManaging(!managing)}>{managing?"Fermer":"＋ Gérer"}</button></div></div>
     {managing&&<div className="team-manager"><form onSubmit={addPerson}><input required value={newPerson.first} onChange={e=>setNewPerson({...newPerson,first:e.target.value})} placeholder="Prénom"/><input required value={newPerson.last} onChange={e=>setNewPerson({...newPerson,last:e.target.value})} placeholder="Nom"/><input required value={newPerson.role} onChange={e=>setNewPerson({...newPerson,role:e.target.value})} placeholder="Poste"/><button>Ajouter</button></form><div className="manage-list">{team.map(p=><div key={`${p.first}-${p.last}`}><span><b>{p.first} {p.last}</b><small>{p.role}</small></span><button onClick={()=>removePerson(p)} aria-label={`Supprimer ${p.first} ${p.last}`}>Supprimer</button></div>)}</div></div>}
     <label className="search">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ex. AM pour Amélie, Amine..."/><kbd>A—Z</kbd></label>
     <div className="list">{filtered.map(p=><button key={`${p.first}-${p.last}`} className={`person ${person?.first===p.first&&person?.last===p.last?"selected":""}`} onClick={()=>{setPerson(p);setSign("")}}><b className={p.color}>{p.first[0]}{p.last[0]}</b><span><strong>{p.first} {p.last}</strong><small>{p.role}</small></span><i>{person?.first===p.first&&person?.last===p.last?"✓":""}</i></button>)}{!filtered.length&&<p className="empty">Aucun nom trouvé.</p>}</div>
    </section>
    <section className={`card signcard ${!person?"disabled":""}`}><div className="cardhead"><span>2</span><div><h2>Signez et validez</h2><p>{person?`Pointage de ${person.first} ${person.last}`:"Sélectionnez d’abord votre nom."}</p></div></div>
     <div className="switch"><button className={mode==="Arrivée"?"active":""} onClick={()=>setMode("Arrivée")}>↘ Arrivée</button><button className={mode==="Départ"?"active":""} onClick={()=>setMode("Départ")}>↗ Départ</button></div>
     <div className="time"><small>HEURE ACTUELLE</small><strong>{new Intl.DateTimeFormat("fr-FR",{hour:"2-digit",minute:"2-digit"}).format(new Date())}</strong></div><label className="caption">VOTRE SIGNATURE</label>
     <Signature key={person?.first||"none"} setValue={setSign}/><button className="primary" disabled={!person||!sign||busy} onClick={submit}>{busy?"Enregistrement...":`Valider mon ${mode.toLowerCase()}`} →</button><p className="privacy">🔒 Votre signature sert uniquement à confirmer ce pointage.</p>
    </section>
   </div>:tab==="details"?<div className="grid details">
    <section className="card"><div className="cardhead"><span>1</span><div><h2>Ajouter les détails</h2><p>Complétez les informations du service.</p></div></div><form onSubmit={add}>
     <h3>MATIN</h3><div className="fields"><label>Caissier du matin<input required value={form.cashierMorning} onChange={e=>setForm({...form,cashierMorning:e.target.value})} placeholder="Nom et prénom"/></label><label>FDC initial / matin<input required value={form.fdcMorning} onChange={e=>setForm({...form,fdcMorning:e.target.value})} placeholder="Ex. 250,00 €"/></label></div>
     <h3 className="night">SOIR</h3><div className="fields"><label>Caissier du soir<input required value={form.cashierEvening} onChange={e=>setForm({...form,cashierEvening:e.target.value})} placeholder="Nom et prénom"/></label><label>FDC du soir<input required value={form.fdcEvening} onChange={e=>setForm({...form,fdcEvening:e.target.value})} placeholder="Ex. 248,50 €"/></label></div>
     <button className="primary full" disabled={busy}>{busy?"Ajout...":"Ajouter la ligne au registre ＋"}</button>
    </form></section>
    <section className="card report-card"><div className="cardhead"><span>2</span><div><h2>Heures des employés</h2><p>Calcul automatique et correction des pointages.</p></div></div><div className="report-tools"><label>Date<input type="date" value={reportDate} onChange={e=>setReportDate(e.target.value)}/></label><button onClick={downloadReport}>↓ Télécharger le fichier</button></div><div className="report-table"><table><thead><tr><th>Employé</th><th>Début 1</th><th>Fin 1</th><th>MIDI</th><th>Début 2</th><th>Fin 2</th><th>SOIR</th><th>Total</th></tr></thead><tbody>{team.map(p=>{const s=summary(p);return <tr key={`${p.first}-${p.last}`}><td>{s.name}</td><td>{s.start1}</td><td>{s.end1}</td><td>{s.hours1.toFixed(2)}</td><td>{s.start2}</td><td>{s.end2}</td><td>{s.hours2.toFixed(2)}</td><td><b>{(s.hours1+s.hours2).toFixed(2)}</b></td></tr>})}</tbody></table></div><div className="attendance-editor"><h3>CORRIGER UN HORAIRE</h3>{attendancePairs.length?attendancePairs.map(pair=><div className="attendance-edit-row attendance-pair-row" key={`${pair.name}-${pair.index}`}><span><b>{pair.name}</b><small>Service {pair.index}</small></span><label>Arrivée<input disabled={!pair.arrival} type="time" value={pair.arrival?(editingTime[pair.arrival.id]??new Date(pair.arrival.timestamp).toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"})):""} onChange={e=>pair.arrival&&setEditingTime({...editingTime,[pair.arrival.id]:e.target.value})}/></label><label>Départ<input disabled={!pair.departure} type="time" value={pair.departure?(editingTime[pair.departure.id]??new Date(pair.departure.timestamp).toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"})):""} onChange={e=>pair.departure&&setEditingTime({...editingTime,[pair.departure.id]:e.target.value})}/></label><button disabled={busy} onClick={()=>updateAttendancePair(pair)}>Modifier</button></div>):<p>Aucun pointage pour cette date.</p>}</div></section>
   </div>:<SuperAdminDashboard/>}
  </section><footer><b>Présence</b><span>Pointage simple, équipe sereine.</span><small><i/> Synchronisation Google prête</small></footer>
 </main>
}
