export type ExcelPerson={first:string;last:string};
export type ExcelAttendance={name:string;type:"Arrivée"|"Départ";timestamp:string;workDate:string;scheduledStartMinutes?:number|null};

const xml=(value:string)=>value.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
const employeeSummary=(person:ExcelPerson,records:ExcelAttendance[],date:string)=>{
  const events=records.filter(record=>record.name===`${person.first} ${person.last}`&&record.workDate===date).sort((a,b)=>a.timestamp.localeCompare(b.timestamp)),shifts:{start?:Date;end?:Date}[]=[];
  for(const event of events){if(event.type==="Arrivée"){let start=new Date(event.timestamp);if(!shifts.length&&event.scheduledStartMinutes!=null){const planned=new Date(`${event.workDate}T00:00:00`);planned.setMinutes(event.scheduledStartMinutes);if(start<planned)start=planned}shifts.push({start})}else{const open=[...shifts].reverse().find(shift=>shift.start&&!shift.end);if(open)open.end=new Date(event.timestamp)}}
  const duration=(shift?:{start?:Date;end?:Date})=>shift?.start&&shift.end?Math.max(0,(shift.end.getTime()-shift.start.getTime())/3600000):0,time=(value?:Date)=>value?value.toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"}):"00:00",hours1=duration(shifts[0]),hours2=duration(shifts[1]);
  return{name:`${person.first} ${person.last}`,start1:time(shifts[0]?.start),end1:time(shifts[0]?.end),hours1,start2:time(shifts[1]?.start),end2:time(shifts[1]?.end),hours2,total:hours1+hours2};
};

export function downloadDailyExcel(date:string,people:ExcelPerson[],records:ExcelAttendance[]){
  const cell=(value:string,type="String",style="")=>`<Cell${style?` ss:StyleID="${style}"`:""}><Data ss:Type="${type}">${xml(value)}</Data></Cell>`;
  const rows=people.map(person=>employeeSummary(person,records,date)).map(row=>`<Row>${cell(row.name)}${cell(row.start1)}${cell(row.end1)}${cell(String(row.hours1),"Number","decimal")}${cell(row.start2)}${cell(row.end2)}${cell(String(row.hours2),"Number","decimal")}${cell(String(row.total),"Number","total")}</Row>`).join("");
  const headers=["Employé","Heure début 1","Heure fin 1","Différence MIDI","Heure début 2","Heure fin 2","Différence SOIR","Heures totales"].map(value=>cell(value,"String","header")).join("");
  const workbookXml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Styles><Style ss:ID="Default"><Alignment ss:Vertical="Center"/><Font ss:FontName="Poppins" ss:Size="10"/></Style><Style ss:ID="title"><Font ss:Bold="1" ss:Size="15" ss:Color="#B51F2A"/><Alignment ss:Horizontal="Center"/></Style><Style ss:ID="header"><Font ss:Bold="1" ss:Color="#FFFFFF"/><Interior ss:Color="#B51F2A" ss:Pattern="Solid"/><Alignment ss:Horizontal="Center"/></Style><Style ss:ID="decimal"><NumberFormat ss:Format="0.00"/></Style><Style ss:ID="total"><Font ss:Bold="1"/><NumberFormat ss:Format="0.00"/></Style></Styles><Worksheet ss:Name="Pointage ${xml(date)}"><Table><Column ss:Width="150"/><Column ss:Width="80" ss:Span="5"/><Column ss:Width="85"/><Column ss:Width="85"/><Row ss:Height="28"><Cell ss:MergeAcross="7" ss:StyleID="title"><Data ss:Type="String">BEEF HOUSE - POINTAGE DU ${xml(date)}</Data></Cell></Row><Row>${headers}</Row>${rows}</Table><WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel"><FreezePanes/><FrozenNoSplit/><SplitHorizontal>2</SplitHorizontal><TopRowBottomPane>2</TopRowBottomPane></WorksheetOptions></Worksheet></Workbook>`;
  const blob=new Blob(["\ufeff",workbookXml],{type:"application/vnd.ms-excel;charset=utf-8"}),url=URL.createObjectURL(blob),link=window.document.createElement("a");link.href=url;link.download=`pointage-${date}.xls`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
