import {useCallback,useEffect,useState} from "react";
import SuperAdminDashboard from "./SuperAdminDashboard";
import {apiUrl} from "./apiUrl";
import "./hyperadmin.css";
import "./hyperadmin-theme.css";

type Restaurant={id:number;name:string;slug:string;address:string;active:number;createdAt:string;administrators:number};
type HyperData={stats:{restaurants:number;activeRestaurants:number;administrators:number;employees:number};restaurants:Restaurant[]};
const request=async(payload:object)=>{const token=localStorage.getItem("presence-token")||sessionStorage.getItem("presence-token"),response=await fetch(apiUrl(),{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token||""}`},body:JSON.stringify(payload)}),raw=await response.text();let result:any;try{result=JSON.parse(raw)}catch{throw new Error(`Réponse invalide du serveur (${response.status}). Vérifiez VITE_API_URL.`)}if(!response.ok||result.success===false)throw new Error(result.message||"Erreur serveur");return result};

export default function HyperAdminDashboard(){
 const[section,setSection]=useState<"restaurants"|"operations">("restaurants"),[data,setData]=useState<HyperData|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const[form,setForm]=useState({name:"",slug:"",address:"",username:"",password:""});
 const refresh=useCallback(async()=>{try{setData(await request({action:"hyperDashboard"}));setError("")}catch(e){setError(e instanceof Error?e.message:"Chargement impossible")}},[]);
 useEffect(()=>{void refresh()},[refresh]);
 const createRestaurant=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await request({action:"createRestaurant",...form});setForm({name:"",slug:"",address:"",username:"",password:""});await refresh()}catch(err){setError(err instanceof Error?err.message:"Création impossible")}finally{setBusy(false)}};
 const toggle=async(id:number)=>{try{await request({action:"toggleRestaurant",id});await refresh()}catch(err){setError(err instanceof Error?err.message:"Modification impossible")}};
 return <section className="hyper-dashboard"><div className="hyper-heading"><div><small>HYPER ADMINISTRATION</small><h2>Réseau BEEF HOUSE</h2><p>Administration centrale des restaurants et de leurs accès.</p></div><span>◆ ACCÈS GLOBAL</span></div><nav className="hyper-nav"><button className={section==="restaurants"?"active":""} onClick={()=>setSection("restaurants")}>Restaurants</button><button className={section==="operations"?"active":""} onClick={()=>setSection("operations")}>Administration complète</button></nav>{error&&<div className="super-alert">{error}<button onClick={()=>setError("")}>×</button></div>}{section==="operations"?<SuperAdminDashboard/>:<>{data&&<div className="hyper-stats"><article><span>Restaurants</span><strong>{data.stats.restaurants}</strong></article><article><span>Restaurants actifs</span><strong>{data.stats.activeRestaurants}</strong></article><article><span>Administrateurs</span><strong>{data.stats.administrators}</strong></article><article><span>Employés actifs</span><strong>{data.stats.employees}</strong></article></div>}<div className="hyper-layout"><article className="super-panel"><div className="panel-title"><div><h3>Les restaurants</h3><p>Établissements enregistrés dans le réseau</p></div></div><div className="restaurant-list">{data?.restaurants.map(restaurant=><div key={restaurant.id}><span className="restaurant-mark">BH</span><div><strong>{restaurant.name}</strong><small>{restaurant.address||restaurant.slug} · {restaurant.administrators} administrateur(s)</small></div><span className={`restaurant-status ${restaurant.active?"active":"inactive"}`}>{restaurant.active?"Actif":"Suspendu"}</span><button onClick={()=>toggle(restaurant.id)}>{restaurant.active?"Suspendre":"Activer"}</button></div>)}</div></article><article className="super-panel restaurant-create"><div className="panel-title"><div><h3>Nouveau restaurant</h3><p>Créer l’établissement et son premier Super Admin</p></div></div><form onSubmit={createRestaurant}><label>Nom du restaurant<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex. BEEF HOUSE Lyon"/></label><label>Identifiant URL<input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})} placeholder="Créé automatiquement"/></label><label>Adresse<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="Adresse de l’établissement"/></label><label>Identifiant du Super Admin<input required minLength={3} value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>Mot de passe initial<input required minLength={8} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><button disabled={busy}>{busy?"Création…":"Créer le restaurant →"}</button></form></article></div></>}</section>
}
