import {useEffect,useMemo,useState} from "react";

type Item={name:string;price:number;quantity:number};
type Person={id:string;name:string;paymentMethod:"ESP"|"CB";paid:boolean;items:Item[]};
type Order={id?:number;workDate:string;tableLabel:string;total:number;people:Person[]};
type Api=(data:object)=>Promise<any>;

const MENU=[
 ["Apéro","Chicken tenders",5.5],["Apéro","Fish tenders",5.5],["Salades","Caesar salade",16],["Salades","Little Italia",16],
 ["Viandes","Entrecôte d’Argentine",29],["Viandes","Entrecôte Black Angus USA",34],["Viandes","Bavette Black Angus USA",29],["Viandes","Cœur de rumsteak Argentine",24],
 ["Formules","Formule classic",17],["Formules","Formule deluxe",18],["Formules","Formule kids",9.5],
 ["Accompagnements","Frites au cheddar",4.5],["Accompagnements","Ratatouille",6.5],["Accompagnements","Gratin dauphinois",6.5],["Accompagnements","Purée à l’huile de truffes",6.5],
 ["Burgers","Classic cheeseburger",15],["Burgers","Bacon cheeseburger",16],["Burgers","Beefhouse burger",18],["Burgers","Montagnard burger",17],["Burgers","Crunchy BBQ",16],["Burgers","Black pepper",16],["Burgers","French burger",17],["Burgers","Chicken crispy",16],["Burgers","Tribeca burger",19],["Burgers","Fish burger",19],
 ["Tacos","American cheesy tacos",11.5],["Tacos","Bacon american cheesy tacos",11.5],["Tacos","Mexican cheesy tacos",11.5],["Tacos","Black pepper tacos",11.5],["Tacos","Chicken crispy tacos",11.5],["Tacos","Vegetarian tacos",11.5],
 ["Boissons","Coca-Cola 33cl",2.5],["Boissons","Coca Zéro 33cl",2.5],["Boissons","Oasis orange 33cl",2.5],["Boissons","Fuze Tea pêche 33cl",2.5],["Boissons","Perrier 33cl",2.5],["Boissons","Eau 50cl",2.5]
] as const;
const euro=(value:number)=>value.toLocaleString("fr-FR",{style:"currency",currency:"EUR"});
const blank=():Order=>({workDate:new Date().toLocaleDateString("en-CA"),tableLabel:"",total:0,people:[]});
const subtotal=(person:Person)=>person.items.reduce((sum,item)=>sum+item.price*item.quantity,0);

export default function OrderSplitDashboard({api}:{api:Api}){
 const[order,setOrder]=useState<Order>(blank()),[orders,setOrders]=useState<Order[]>([]),[selectedPerson,setSelectedPerson]=useState(""),[menuSearch,setMenuSearch]=useState(""),[custom,setCustom]=useState({name:"",price:""}),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const load=async()=>{try{const result=await api({action:"orderSplits",workDate:order.workDate});setOrders(result.orders||[])}catch(error){setMessage(error instanceof Error?error.message:"Chargement impossible")}};
 useEffect(()=>{void load()},[order.workDate]);
 const assigned=order.people.reduce((sum,person)=>sum+subtotal(person),0),paid=order.people.filter(person=>person.paid).reduce((sum,person)=>sum+subtotal(person),0),remaining=Math.max(0,order.total-paid),unassigned=order.total-assigned;
 const current=order.people.find(person=>person.id===selectedPerson),filtered=useMemo(()=>MENU.filter(item=>`${item[0]} ${item[1]}`.toLowerCase().includes(menuSearch.toLowerCase())),[menuSearch]);
 const change=(id:string,fn:(person:Person)=>Person)=>setOrder(value=>({...value,people:value.people.map(person=>person.id===id?fn(person):person)}));
 const addPerson=()=>{const person:Person={id:crypto.randomUUID(),name:`Personne ${order.people.length+1}`,paymentMethod:"ESP",paid:false,items:[]};setOrder(value=>({...value,people:[...value.people,person]}));setSelectedPerson(person.id)};
 const addItem=(name:string,price:number)=>{if(!current)return;change(current.id,person=>{const found=person.items.find(item=>item.name===name&&item.price===price);return{...person,items:found?person.items.map(item=>item===found?{...item,quantity:item.quantity+1}:item):[...person.items,{name,price,quantity:1}]}})};
 const save=async()=>{setBusy(true);try{const result=await api({action:"saveOrderSplit",...order});setOrder(value=>({...value,id:result.id||value.id}));setMessage("Séparation enregistrée.");await load()}catch(error){setMessage(error instanceof Error?error.message:"Enregistrement impossible")}finally{setBusy(false)}};
 const removeOrder=async(id?:number)=>{if(!id||!confirm("Supprimer cette séparation ?"))return;await api({action:"deleteOrderSplit",id});if(order.id===id)setOrder(blank());await load()};
 return <div className="order-split">
  {message&&<p className="split-message">{message}</p>}
  <section className="card split-summary"><div className="cardhead"><span>÷</span><div><h2>Commande à répartir</h2><p>Saisissez le total puis attribuez les consommations à chaque personne.</p></div></div><div className="split-top"><label>Date<input type="date" value={order.workDate} onChange={e=>setOrder({...order,workDate:e.target.value})}/></label><label>Table / commande<input value={order.tableLabel} onChange={e=>setOrder({...order,tableLabel:e.target.value})} placeholder="Ex. Table 12"/></label><label>Total commande (€)<input type="number" min="0" step="0.01" value={order.total||""} onChange={e=>setOrder({...order,total:Number(e.target.value)})}/></label><button onClick={addPerson}>＋ Ajouter une personne</button></div><div className="split-totals"><span>Total <b>{euro(order.total)}</b></span><span>Attribué <b>{euro(assigned)}</b></span><span>Payé <b>{euro(paid)}</b></span><span className={remaining?"due":"ok"}>Reste à encaisser <b>{euro(remaining)}</b></span><span className={Math.abs(unassigned)>.009?"warning":"ok"}>Écart commande <b>{euro(unassigned)}</b></span></div></section>
  <div className="split-workspace"><section className="card people-panel"><h3>PERSONNES</h3>{order.people.map(person=><article className={selectedPerson===person.id?"selected":""} key={person.id} onClick={()=>setSelectedPerson(person.id)}><input value={person.name} onClick={e=>e.stopPropagation()} onChange={e=>change(person.id,p=>({...p,name:e.target.value}))}/><strong>{euro(subtotal(person))}</strong><div><button className={person.paymentMethod==="ESP"?"active":""} onClick={e=>{e.stopPropagation();change(person.id,p=>({...p,paymentMethod:"ESP"}))}}>ESP</button><button className={person.paymentMethod==="CB"?"active":""} onClick={e=>{e.stopPropagation();change(person.id,p=>({...p,paymentMethod:"CB"}))}}>CB</button><button className={person.paid?"paid":"unpaid"} onClick={e=>{e.stopPropagation();change(person.id,p=>({...p,paid:!p.paid}))}}>{person.paid?"✓ Payé":"Non payé"}</button><button className="remove" onClick={e=>{e.stopPropagation();setOrder(value=>({...value,people:value.people.filter(p=>p.id!==person.id)}));setSelectedPerson("")}}>×</button></div></article>)}{!order.people.length&&<p className="split-empty">Ajoutez une personne pour commencer.</p>}</section>
  <section className="card menu-panel"><h3>CONSOMMATIONS {current&&`· ${current.name}`}</h3>{current?<><div className="current-items">{current.items.map((item,index)=><div key={`${item.name}-${index}`}><span>{item.quantity} × {item.name}<small>{euro(item.price)}</small></span><b>{euro(item.price*item.quantity)}</b><button onClick={()=>change(current.id,p=>({...p,items:p.items.filter((_,i)=>i!==index)}))}>×</button></div>)}{!current.items.length&&<p>Aucun article sélectionné.</p>}</div><input className="menu-search" value={menuSearch} onChange={e=>setMenuSearch(e.target.value)} placeholder="Rechercher dans le menu…"/><div className="menu-grid">{filtered.map(item=><button key={item[1]} onClick={()=>addItem(item[1],item[2])}><small>{item[0]}</small><b>{item[1]}</b><span>{euro(item[2])}</span></button>)}</div><div className="custom-item"><input value={custom.name} onChange={e=>setCustom({...custom,name:e.target.value})} placeholder="Article libre"/><input type="number" min="0" step="0.01" value={custom.price} onChange={e=>setCustom({...custom,price:e.target.value})} placeholder="Prix €"/><button onClick={()=>{const price=Number(custom.price);if(custom.name.trim()&&Number.isFinite(price)){addItem(custom.name.trim(),price);setCustom({name:"",price:""})}}}>Ajouter</button></div></>:<p className="split-empty">Sélectionnez une personne à gauche.</p>}</section></div>
  <button className="save-split" disabled={busy||!order.people.length} onClick={save}>{busy?"Enregistrement…":"Enregistrer la séparation"}</button>
  <section className="card saved-orders"><h3>SÉPARATIONS DU JOUR</h3>{orders.map(saved=><article key={saved.id} onClick={()=>{setOrder(saved);setSelectedPerson(saved.people[0]?.id||"")}}><span><b>{saved.tableLabel||`Commande #${saved.id}`}</b><small>{saved.people.length} personne(s)</small></span><strong>{euro(saved.total)}</strong><button onClick={e=>{e.stopPropagation();void removeOrder(saved.id)}}>×</button></article>)}{!orders.length&&<p className="split-empty">Aucune séparation enregistrée pour cette date.</p>}</section>
 </div>
}
