import {useEffect,useMemo,useState} from "react";

type Item={name:string;price:number;quantity:number};
type Person={id:string;name:string;paymentMethod:"ESP"|"CB";paid:boolean;items:Item[]};
type Order={id?:number;workDate:string;tableLabel:string;total:number;people:Person[]};
type Api=(data:object)=>Promise<any>;

const MENU=[
 ["Entrées & Salades","Foie gras de canard",25],["Entrées & Salades","Camembert rôti au four",18],["Entrées & Salades","Carpaccio de bœuf classique",18],["Supplément","Burrata pour carpaccio",5],["Entrées & Salades","Os à moelle grillé",12],["Entrées & Salades","Salade César au poulet grillé",19],["Entrées & Salades","Salade Beef House",22],
 ["Plats Signature","Saucisses de veau à l’italienne",25],["Plats Signature","Cordon bleu maison",25],["Plats Signature","Travers de bœuf fumés",34],["Plats Signature","Tournedos Rossini",54],["Plats Signature","Souris d’agneau confite",39],["Plats Signature","1/4 de poulet fermier grillé",18],
 ["Pièces du Boucher","Entrecôte",32],["Pièces du Boucher","Tartare de bœuf",25],["Supplément","Cuisson du tartare",3],["Pièces du Boucher","Faux-filet",30],["Pièces du Boucher","Magret de canard grillé",32],["Pièces du Boucher","Rumsteck",28],["Pièces du Boucher","Côtelettes d’agneau grillées",32],["Pièces du Boucher","Bavette d’aloyau",29],["Pièces du Boucher","Côte de bœuf",49],["Pièces du Boucher","Filet de bœuf",35],["Pièces du Boucher","Côte de veau grillée",39],["Pièces du Boucher","Filet mignon de veau",39],
 ["La Baguette","Le French Classic",18],["La Baguette","Le Bœuf Comté",16],["La Baguette","Le Poulet Fermier",15],
 ["Poissons","1/2 langouste rôtie",45],["Poissons","Pavé de saumon grillé",32],["Poissons","Steak de thon grillé",35],
 ["Plat Enfant","Steak haché & frites",12],["Plat Enfant","Poulet popcorn & frites",12]
] as const;
const euro=(value:number)=>value.toLocaleString("fr-FR",{style:"currency",currency:"EUR"});
const blank=():Order=>({workDate:new Date().toLocaleDateString("en-CA"),tableLabel:"",total:0,people:[]});
const subtotal=(person:Person)=>person.items.reduce((sum,item)=>sum+item.price*item.quantity,0);

export default function OrderSplitDashboard({api}:{api:Api}){
 const[order,setOrder]=useState<Order>(blank()),[orders,setOrders]=useState<Order[]>([]),[selectedPerson,setSelectedPerson]=useState(""),[peopleCount,setPeopleCount]=useState("1"),[menuSearch,setMenuSearch]=useState(""),[custom,setCustom]=useState({name:"",price:"",quantity:"1"}),[drink,setDrink]=useState({name:"",price:"",quantity:"1"}),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const load=async()=>{try{const result=await api({action:"orderSplits",workDate:order.workDate});setOrders(result.orders||[])}catch(error){setMessage(error instanceof Error?error.message:"Chargement impossible")}};
 useEffect(()=>{void load()},[order.workDate]);
 const assigned=order.people.reduce((sum,person)=>sum+subtotal(person),0),paid=order.people.filter(person=>person.paid).reduce((sum,person)=>sum+subtotal(person),0),remaining=Math.max(0,order.total-paid),unassigned=order.total-assigned;
 const current=order.people.find(person=>person.id===selectedPerson),filtered=useMemo(()=>MENU.filter(item=>`${item[0]} ${item[1]}`.toLowerCase().includes(menuSearch.toLowerCase())),[menuSearch]);
 const change=(id:string,fn:(person:Person)=>Person)=>setOrder(value=>({...value,people:value.people.map(person=>person.id===id?fn(person):person)}));
 const createPeople=()=>{const count=Math.min(50,Math.max(1,Math.floor(Number(peopleCount)||1))),created=Array.from({length:count},(_,index):Person=>({id:crypto.randomUUID(),name:`Personne ${order.people.length+index+1}`,paymentMethod:"ESP",paid:false,items:[]}));setOrder(value=>({...value,people:[...value.people,...created]}));setSelectedPerson(created[0].id)};
 const addItem=(name:string,price:number)=>{if(!current)return;change(current.id,person=>{const found=person.items.find(item=>item.name===name&&item.price===price);return{...person,items:found?person.items.map(item=>item===found?{...item,quantity:item.quantity+1}:item):[...person.items,{name,price,quantity:1}]}})};
 const addManual=(entry:{name:string;price:string;quantity:string},reset:()=>void)=>{if(!current)return;const price=Number(entry.price),quantity=Math.max(1,Math.floor(Number(entry.quantity)||1));if(!entry.name.trim()||!Number.isFinite(price)||price<0)return;change(current.id,person=>({...person,items:[...person.items,{name:entry.name.trim(),price,quantity}]}));reset()};
 const save=async()=>{setBusy(true);try{const result=await api({action:"saveOrderSplit",...order});setOrder(value=>({...value,id:result.id||value.id}));setMessage("Séparation enregistrée.");await load()}catch(error){setMessage(error instanceof Error?error.message:"Enregistrement impossible")}finally{setBusy(false)}};
 const removeOrder=async(id?:number)=>{if(!id||!confirm("Supprimer cette séparation ?"))return;await api({action:"deleteOrderSplit",id});if(order.id===id)setOrder(blank());await load()};
 return <div className="order-split">
  {message&&<p className="split-message">{message}</p>}
  <section className="card split-summary"><div className="cardhead"><span>÷</span><div><h2>Commande à répartir</h2><p>Saisissez le total puis attribuez les consommations à chaque personne.</p></div></div><div className="split-top"><label>Date<input type="date" value={order.workDate} onChange={e=>setOrder({...order,workDate:e.target.value})}/></label><label>Table / commande<input value={order.tableLabel} onChange={e=>setOrder({...order,tableLabel:e.target.value})} placeholder="Ex. Table 12"/></label><label>Total commande (€)<input type="number" min="0" step="0.01" value={order.total||""} onChange={e=>setOrder({...order,total:Number(e.target.value)})}/></label><label>Nombre de personnes<input type="number" min="1" max="50" step="1" value={peopleCount} onChange={e=>setPeopleCount(e.target.value)}/></label><button onClick={createPeople}>Créer les personnes</button></div><div className="split-totals"><span>Total <b>{euro(order.total)}</b></span><span>Attribué <b>{euro(assigned)}</b></span><span>Payé <b>{euro(paid)}</b></span><span className={remaining?"due":"ok"}>Reste à encaisser <b>{euro(remaining)}</b></span><span className={Math.abs(unassigned)>.009?"warning":"ok"}>Écart commande <b>{euro(unassigned)}</b></span></div></section>
  <div className="split-workspace"><section className="card people-panel"><h3>PERSONNES</h3>{order.people.map(person=><article className={selectedPerson===person.id?"selected":""} key={person.id} onClick={()=>setSelectedPerson(person.id)}><input value={person.name} onClick={e=>e.stopPropagation()} onChange={e=>change(person.id,p=>({...p,name:e.target.value}))}/><strong>{euro(subtotal(person))}</strong><div><button className={person.paymentMethod==="ESP"?"active":""} onClick={e=>{e.stopPropagation();change(person.id,p=>({...p,paymentMethod:"ESP"}))}}>ESP</button><button className={person.paymentMethod==="CB"?"active":""} onClick={e=>{e.stopPropagation();change(person.id,p=>({...p,paymentMethod:"CB"}))}}>CB</button><button className={person.paid?"paid":"unpaid"} onClick={e=>{e.stopPropagation();change(person.id,p=>({...p,paid:!p.paid}))}}>{person.paid?"✓ Payé":"Non payé"}</button><button className="remove" onClick={e=>{e.stopPropagation();setOrder(value=>({...value,people:value.people.filter(p=>p.id!==person.id)}));setSelectedPerson("")}}>×</button></div></article>)}{!order.people.length&&<p className="split-empty">Ajoutez une personne pour commencer.</p>}</section>
  <section className="card menu-panel"><h3>CONSOMMATIONS {current&&`· ${current.name}`}</h3>{current?<><div className="current-items">{current.items.map((item,index)=><div key={`${item.name}-${index}`}><span>{item.quantity} × {item.name}<small>{euro(item.price)}</small></span><b>{euro(item.price*item.quantity)}</b><button onClick={()=>change(current.id,p=>({...p,items:p.items.filter((_,i)=>i!==index)}))}>×</button></div>)}{!current.items.length&&<p>Aucun article sélectionné.</p>}</div><input className="menu-search" value={menuSearch} onChange={e=>setMenuSearch(e.target.value)} placeholder="Rechercher dans le menu…"/><div className="menu-grid">{filtered.map(item=><button key={item[1]} onClick={()=>addItem(item[1],item[2])}><small>{item[0]}</small><b>{item[1]}</b><span>{euro(item[2])}</span></button>)}</div><h4>BOISSON — PRIX MANUEL</h4><div className="custom-item drink-item"><input value={drink.name} onChange={e=>setDrink({...drink,name:e.target.value})} placeholder="Nom de la boisson"/><input type="number" min="0" step="0.01" value={drink.price} onChange={e=>setDrink({...drink,price:e.target.value})} placeholder="Prix €"/><input type="number" min="1" step="1" value={drink.quantity} onChange={e=>setDrink({...drink,quantity:e.target.value})} placeholder="Qté"/><button onClick={()=>addManual(drink,()=>setDrink({name:"",price:"",quantity:"1"}))}>Ajouter la boisson</button></div><h4>AUTRE ARTICLE</h4><div className="custom-item"><input value={custom.name} onChange={e=>setCustom({...custom,name:e.target.value})} placeholder="Article libre"/><input type="number" min="0" step="0.01" value={custom.price} onChange={e=>setCustom({...custom,price:e.target.value})} placeholder="Prix €"/><input type="number" min="1" step="1" value={custom.quantity} onChange={e=>setCustom({...custom,quantity:e.target.value})} placeholder="Qté"/><button onClick={()=>addManual(custom,()=>setCustom({name:"",price:"",quantity:"1"}))}>Ajouter</button></div></>:<p className="split-empty">Sélectionnez une personne à gauche.</p>}</section></div>
  <button className="save-split" disabled={busy||!order.people.length} onClick={save}>{busy?"Enregistrement…":"Enregistrer la séparation"}</button>
  <section className="card saved-orders"><h3>SÉPARATIONS DU JOUR</h3>{orders.map(saved=><article key={saved.id} onClick={()=>{setOrder(saved);setSelectedPerson(saved.people[0]?.id||"")}}><span><b>{saved.tableLabel||`Commande #${saved.id}`}</b><small>{saved.people.length} personne(s)</small></span><strong>{euro(saved.total)}</strong><button onClick={e=>{e.stopPropagation();void removeOrder(saved.id)}}>×</button></article>)}{!orders.length&&<p className="split-empty">Aucune séparation enregistrée pour cette date.</p>}</section>
 </div>
}
