import { useCallback, useEffect, useMemo, useState } from "react";
import "./planning.css";
import "./manual-planning.css";
import "./planning-services.css";
import { downloadPlanningPdf, viewPlanningPdf } from "./planningPdf";

type Employee={id:number;first:string;last:string;role:string;active:number};
type Block={employeeId:number;workDate:string;startMinutes:number;service?:"matin"|"soir";closing?:number};

const mondayOf=(date:Date)=>{const result=new Date(date);const day=(result.getDay()+6)%7;result.setDate(result.getDate()-day);result.setHours(12,0,0,0);return result};
const iso=(date:Date)=>date.toISOString().slice(0,10);
const addDays=(date:Date,count:number)=>{const result=new Date(date);result.setDate(result.getDate()+count);return result};
const timeLabel=(minutes:number)=>`${String(Math.floor(minutes/60)%24).padStart(2,"0")}:${String(minutes%60).padStart(2,"0")}`;
const timeToMinutes=(value:string)=>{const[hours,minutes]=value.split(":").map(Number);return (hours<7?hours+24:hours)*60+minutes};

export default function Planning({employees,request}:{employees:Employee[];request:(payload:object)=>Promise<any>}){
  const activeEmployees=employees.filter(employee=>employee.active);
  const[planningGroup,setPlanningGroup]=useState<"salle"|"cuisine">("salle");
  const displayedEmployees=activeEmployees.filter(employee=>String(employee.role).toLocaleLowerCase("fr").includes("cuisine")?(planningGroup==="cuisine"):(planningGroup==="salle"));
  const[week,setWeek]=useState(()=>mondayOf(new Date())),[blocks,setBlocks]=useState<Block[]>([]),[busyKey,setBusyKey]=useState(""),[manualBusy,setManualBusy]=useState(false),[manualError,setManualError]=useState(""),[selectorVisible,setSelectorVisible]=useState(true);
  const[manual,setManual]=useState(()=>({employeeId:"",workDate:iso(new Date()),service:"matin" as "matin"|"soir",start:"09:00",end:"17:00",closing:false}));
  const days=useMemo(()=>Array.from({length:7},(_,index)=>addDays(week,index)),[week]);
  const visibleDays=useMemo(()=>{const today=iso(new Date());return days.filter(day=>iso(day)>=today)},[days]);
  const slots=useMemo(()=>Array.from({length:38},(_,index)=>420+index*30),[]);
  const load=useCallback(async()=>{const result=await request({action:"getSchedule",weekStart:iso(week)});setBlocks(result.blocks||[])},[request,week]);
  useEffect(()=>{void load()},[load]);
  useEffect(()=>{if(!displayedEmployees.some(employee=>String(employee.id)===manual.employeeId))setManual(current=>({...current,employeeId:displayedEmployees[0]?String(displayedEmployees[0].id):""}))},[displayedEmployees,manual.employeeId]);
  const selected=new Set(blocks.map(block=>`${block.employeeId}-${block.workDate}-${block.startMinutes}`));
  const toggle=async(employeeId:number,workDate:string,startMinutes:number)=>{const key=`${employeeId}-${workDate}-${startMinutes}`,wasSelected=selected.has(key);setBusyKey(key);setBlocks(current=>wasSelected?current.filter(block=>`${block.employeeId}-${block.workDate}-${block.startMinutes}`!==key):[...current,{employeeId,workDate,startMinutes}]);try{await request({action:"toggleScheduleBlock",employeeId,workDate,startMinutes})}catch{await load()}finally{setBusyKey("")}};
  const saveManual=async(e:React.FormEvent)=>{e.preventDefault();const startMinutes=timeToMinutes(manual.start),endMinutes=manual.closing?1560:timeToMinutes(manual.end);setManualBusy(true);setManualError("");try{await request({action:"setScheduleRange",employeeId:Number(manual.employeeId),workDate:manual.workDate,service:manual.service,startMinutes,endMinutes,closing:manual.closing});const targetWeek=mondayOf(new Date(`${manual.workDate}T12:00:00`));if(iso(targetWeek)===iso(week))await load();else setWeek(targetWeek)}catch(error){setManualError(error instanceof Error?error.message:"Enregistrement impossible")}finally{setManualBusy(false)}};
  return <article className="super-panel planning-panel">
    <div className="panel-title planning-title"><div><h3>Planning hebdomadaire · {planningGroup==="cuisine"?"Cuisine":"Salle"}</h3><p>Méthode 1 · cliquez sur les cubes de 30 minutes</p></div><div className="planning-actions"><button className="selector-toggle" onClick={()=>setSelectorVisible(value=>!value)}>{selectorVisible?"▴ Masquer la grille":"▾ Afficher la grille"}</button><button className="preview-button" disabled={!displayedEmployees.length} onClick={()=>viewPlanningPdf(days,displayedEmployees,blocks)}>◉ Visualiser</button><button className="pdf-button" disabled={!displayedEmployees.length} onClick={()=>downloadPlanningPdf(days,displayedEmployees,blocks,`${iso(week)}-${planningGroup}`)}>↓ PDF {planningGroup==="cuisine"?"Cuisine":"Salle"}</button><div className="week-controls"><button onClick={()=>setWeek(addDays(week,-7))}>←</button><strong>{days[0].toLocaleDateString("fr-FR",{day:"2-digit",month:"short"})} — {days[6].toLocaleDateString("fr-FR",{day:"2-digit",month:"short",year:"numeric"})}</strong><button onClick={()=>setWeek(addDays(week,7))}>→</button></div></div></div>
    <div className="planning-group-tabs"><button className={planningGroup==="salle"?"active":""} onClick={()=>setPlanningGroup("salle")}><span>♙</span><b>Planning Salle</b><small>{activeEmployees.length-activeEmployees.filter(employee=>String(employee.role).toLocaleLowerCase("fr").includes("cuisine")).length} employés</small></button><button className={planningGroup==="cuisine"?"active cuisine":"cuisine"} onClick={()=>setPlanningGroup("cuisine")}><span>♨</span><b>Planning Cuisine</b><small>{activeEmployees.filter(employee=>String(employee.role).toLocaleLowerCase("fr").includes("cuisine")).length} employés</small></button></div>
    <form className="manual-planning" onSubmit={saveManual}><div><strong>Méthode 2 · saisie manuelle {planningGroup==="cuisine"?"Cuisine":"Salle"}</strong><small>Ajoutez séparément le service du matin et celui du soir. Les cubes seront mis à jour automatiquement.</small></div><label>Employé<select required value={manual.employeeId} onChange={e=>setManual({...manual,employeeId:e.target.value})}>{displayedEmployees.map(employee=><option value={employee.id} key={employee.id}>{employee.first} {employee.last}</option>)}</select></label><label>Date<input required type="date" min={iso(new Date())} value={manual.workDate} onChange={e=>setManual({...manual,workDate:e.target.value})}/></label><label>Service<select value={manual.service} onChange={e=>{const service=e.target.value as "matin"|"soir";setManual({...manual,service,start:service==="matin"?"09:00":"18:00",end:service==="matin"?"17:00":"02:00",closing:service==="soir"})}}><option value="matin">Matin</option><option value="soir">Soir</option></select></label><label>Début<input required type="time" step="1800" value={manual.start} onChange={e=>setManual({...manual,start:e.target.value})}/></label><label>Fin<input required disabled={manual.closing} type="time" step="1800" value={manual.end} onChange={e=>setManual({...manual,end:e.target.value})}/></label><label className="closing-choice"><input type="checkbox" checked={manual.closing} onChange={e=>setManual({...manual,closing:e.target.checked})}/><span>Jusqu’à<br/><b>FERMETURE</b></span></label><button disabled={manualBusy||!manual.employeeId}>{manualBusy?"Enregistrement…":`Appliquer ${manual.service}`}</button>{manualError&&<p className="super-alert">{manualError}</p>}</form>
    <div className="planning-help"><i/> Le matin et le soir sont indépendants : modifier l’un ne supprime plus l’autre. Ouverture 07:00, fermeture 02:00.</div>
    {selectorVisible&&<div className="planning-scroll">{!displayedEmployees.length?<div className="no-future-days">Aucun employé actif dans le groupe {planningGroup==="cuisine"?"Cuisine":"Salle"}.</div>:visibleDays.length?visibleDays.map(day=>{const workDate=iso(day);return <section className="planning-day" key={workDate}><div className="planning-day-heading"><h4>{day.toLocaleDateString("fr-FR",{weekday:"long",day:"numeric",month:"long"})}</h4></div><div className="planning-grid"><div className="planning-hours"><span>Employé</span>{slots.map((slot,index)=><small key={slot}>{index%2===0?timeLabel(slot):"·"}</small>)}<small className="closing-hour">FERMETURE</small></div>{displayedEmployees.map(employee=><div className="planning-employee" key={employee.id}><span title={`${employee.first} ${employee.last}`}><b>{employee.first} {employee.last}</b><small>{employee.role}</small></span>{slots.map(slot=>{const key=`${employee.id}-${workDate}-${slot}`,active=selected.has(key);return <button key={slot} className={active?"selected":""} disabled={busyKey===key} onClick={()=>toggle(employee.id,workDate,slot)} title={`${employee.first} · ${timeLabel(slot)}–${timeLabel(slot+30)}`} aria-label={`${active?"Retirer":"Ajouter"} ${employee.first} à ${timeLabel(slot)}`}/>})}{(()=>{const key=`${employee.id}-${workDate}-1560`,active=selected.has(key);return <button className={`closing-cell ${active?"selected":""}`} disabled={busyKey===key} onClick={()=>toggle(employee.id,workDate,1560)} title={`${employee.first} · jusqu’à fermeture`} aria-label={`${active?"Retirer":"Ajouter"} fermeture pour ${employee.first}`}/>})()}</div>)}</div></section>}):<div className="no-future-days">Cette semaine est terminée. Passez à la semaine suivante.</div>}</div>}
  </article>;
}
