type PdfEmployee={id:number;first:string;last:string;role:string};
type PdfBlock={employeeId:number;workDate:string;startMinutes:number};
type Range={start:number;end:number};

const ascii=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^\x20-\x7E]/g,"-");
const escapePdf=(value:string)=>ascii(value).replace(/([\\()])/g,"\\$1");
const time=(minutes:number)=>`${String(Math.floor(minutes/60)%24).padStart(2,"0")}:${String(minutes%60).padStart(2,"0")}`;
const groupRanges=(values:number[])=>{const sorted=[...new Set(values)].sort((a,b)=>a-b),ranges:Range[]=[];let start=sorted[0],last=sorted[0];for(const value of sorted.slice(1)){if(value===last+30){last=value;continue}ranges.push({start,end:last+30});start=last=value}if(start!==undefined)ranges.push({start,end:last+30});return ranges};
const text=(x:number,y:number,size:number,value:string,bold=false)=>`BT /${bold?"F2":"F1"} ${size} Tf ${x.toFixed(1)} ${y.toFixed(1)} Td (${escapePdf(value)}) Tj ET\n`;
const rect=(x:number,y:number,w:number,h:number,fill:string)=>`${fill} rg ${x.toFixed(1)} ${y.toFixed(1)} ${w.toFixed(1)} ${h.toFixed(1)} re B\n`;
const fit=(value:string,max:number)=>value.length<=max?value:`${value.slice(0,Math.max(1,max-1))}.`;
const roleColor=(role:string)=>{const value=role.toLowerCase();if(value.includes("caisse"))return"1 0.96 0.55";if(value.includes("cuisine")||value.includes("bar"))return"0.96 0.68 0.68";if(value.includes("service")||value.includes("salle"))return"0.78 0.87 0.98";if(value.includes("accueil"))return"0.82 0.92 0.80";return"0.93 0.93 0.94"};

export function buildPlanningPdf(days:Date[],employees:PdfEmployee[],blocks:PdfBlock[]){
  const width=1191,height=842,margin=18,nameWidth=145,tableWidth=width-margin*2,cellWidth=(tableWidth-nameWidth)/14;
  const titleY=height-34,dayHeaderY=height-92,subHeaderY=height-114,rowTop=height-136,legendTop=105,rowHeight=Math.min(25,Math.max(14,(rowTop-legendTop)/Math.max(1,employees.length)));
  const weekLabel=`SEMAINE DU ${days[0].toLocaleDateString("fr-FR",{day:"2-digit",month:"2-digit"})} AU ${days[6].toLocaleDateString("fr-FR",{day:"2-digit",month:"2-digit",year:"numeric"})}`;
  let stream="0 0 0 RG 0.45 w\n"+text(margin,titleY+2,11,"BEEF HOUSE",true)+"0.68 0.06 0.10 rg\n"+text(width/2-weekLabel.length*4.6,titleY,18,weekLabel,true)+"0 0 0 rg\n";
  stream+=rect(margin,dayHeaderY,nameWidth,44,"0.22 0.22 0.22")+"1 1 1 rg\n"+text(margin+38,dayHeaderY+27,9,"EMPLOYE",true)+text(margin+45,dayHeaderY+9,7,"Equipe",false);
  days.forEach((day,index)=>{const x=margin+nameWidth+index*cellWidth*2;stream+=rect(x,dayHeaderY,cellWidth*2,22,"0.22 0.22 0.22")+"1 1 1 rg\n"+text(x+cellWidth-24,dayHeaderY+7,8,day.toLocaleDateString("fr-FR",{weekday:"long"}).toUpperCase(),true)+rect(x,subHeaderY,cellWidth,22,"0.88 0.88 0.88")+rect(x+cellWidth,subHeaderY,cellWidth,22,"0.88 0.88 0.88")+"0.05 0.05 0.05 rg\n"+text(x+cellWidth/2-13,subHeaderY+7,7,"Matin",true)+text(x+cellWidth+cellWidth/2-10,subHeaderY+7,7,"Soir",true)});
  employees.forEach((employee,row)=>{const y=rowTop-(row+1)*rowHeight,fill=row%2?"0.97 0.97 0.97":"1 1 1";stream+=rect(margin,y,nameWidth,rowHeight,fill)+"0.05 0.05 0.05 rg\n"+text(margin+5,y+rowHeight/2-3,7.2,fit(`${employee.first} ${employee.last}`,24),true);days.forEach((day,index)=>{const date=day.toISOString().slice(0,10),ranges=groupRanges(blocks.filter(block=>block.employeeId===employee.id&&block.workDate===date).map(block=>block.startMinutes)),morning=ranges.filter(range=>range.start<1020).map(range=>`${time(range.start)}-${time(range.end)}`).join(" / "),evening=ranges.filter(range=>range.start>=1020).map(range=>`${time(range.start)}-${time(range.end)}`).join(" / "),x=margin+nameWidth+index*cellWidth*2,color=ranges.length?roleColor(employee.role):fill;stream+=rect(x,y,cellWidth,rowHeight,morning?color:fill)+rect(x+cellWidth,y,cellWidth,rowHeight,evening?color:fill)+"0.05 0.05 0.05 rg\n";if(morning)stream+=text(x+3,y+rowHeight/2-3,6.2,fit(morning,15),true);if(evening)stream+=text(x+cellWidth+3,y+rowHeight/2-3,6.2,fit(evening,15),true)})});
  const legend=[{label:"Caisse",color:"1 0.96 0.55"},{label:"Cuisine / Bar",color:"0.96 0.68 0.68"},{label:"Service / Salle",color:"0.78 0.87 0.98"},{label:"Accueil",color:"0.82 0.92 0.80"},{label:"Autre poste",color:"0.93 0.93 0.94"}];
  stream+="0.12 0.12 0.14 rg\n"+text(margin,82,8,"LEGENDE DES COULEURS",true);
  legend.forEach((item,index)=>{const x=margin+index*225;stream+=rect(x,48,34,18,item.color)+"0.12 0.12 0.14 rg\n"+text(x+43,54,8,item.label,true)});
  stream+="0.55 0.55 0.58 RG 0.5 w\n"+`${margin} 35 m ${width-margin} 35 l S\n`+"0.35 0.35 0.38 rg\n"+text(margin,18,7,"Planning genere depuis BEEF HOUSE")+text(width-155,18,7,new Date().toLocaleDateString("fr-FR"));
  const objects=["<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 1191 842] /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 4 0 R >>",`<< /Length ${stream.length} >>\nstream\n${stream}endstream`,"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>"];
  let pdf="%PDF-1.4\n",offsets=[0];objects.forEach((object,index)=>{offsets[index+1]=pdf.length;pdf+=`${index+1} 0 obj\n${object}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;for(let i=1;i<=objects.length;i++)pdf+=`${String(offsets[i]).padStart(10,"0")} 00000 n \n`;pdf+=`trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new TextEncoder().encode(pdf);
}
export function downloadPlanningPdf(days:Date[],employees:PdfEmployee[],blocks:PdfBlock[],weekStart:string){const blob=new Blob([buildPlanningPdf(days,employees,blocks)],{type:"application/pdf"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`planning-semaine-${weekStart}.pdf`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function viewPlanningPdf(days:Date[],employees:PdfEmployee[],blocks:PdfBlock[]){const blob=new Blob([buildPlanningPdf(days,employees,blocks)],{type:"application/pdf"}),url=URL.createObjectURL(blob);window.open(url,"_blank");setTimeout(()=>URL.revokeObjectURL(url),60000)}
